[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/api"
  to = "/api/index.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
